# This is the workflow name
name: 02-Workflow-Events

# ON - this is trigger
on: push

jobs:
  
  echo-hello:
    # To define the type of machine to run the job on.
    runs-on: ubuntu-latest
    #A job contains a sequence of tasks is called steps
    steps:
        - name: Show the trigger
          run: echo "Hello, world!"

